In [211]:
import pandas as pd
import numpy as np

In [212]:
train_df = pd.read_csv('nlp_train.csv')
test_df = pd.read_csv('nlp_test.csv')

In [213]:
train_df['category'].value_counts().index
train_df['target'].value_counts().index
train_df['target'].unique()

array([ 7,  4,  1, 14, 16, 13,  3,  2,  8, 19,  6,  0, 12,  5, 10,  9, 15,
       17, 18, 11], dtype=int64)

In [214]:
# train_df[(train_df['category'] == 'alt.atheism') | (train_df['category'] == 'comp.graphics')]



cols = ['alt.atheism','comp.graphics','sci.space']

train_df = train_df[train_df['category'].isin(cols)]
# train_df['category'].value_counts()


In [215]:
test_df = test_df[test_df['category'].isin(cols)]

# test_df['category'].value_counts()


In [216]:
train_df['category'].unique()

array(['comp.graphics', 'sci.space', 'alt.atheism'], dtype=object)

In [217]:
train_df.iloc[4:5,:].text

print(train_df.iloc[4].text)


I certainly do use it whenever I have to do TIFF, and it usually works
very well.  That's not my point.  I'm >philosophically< opposed to it
because of its complexity.

This complexity has led to some programs' poor TIFF writers making
some very bizarre files, other programs' inability to load TIFF
images (though they'll save them, of course), and a general
inability to interchange images between different environments
despite the fact they all think they understand TIFF.

As the saying goes, "It's not me I'm worried about- it's all the
abuse of TIFF over the years, and I chalk it all up to the immense (and
unnecessary) complexity of the format.

In the words of the TIFF 5.0 spec, Appendix G, page G-1 (capitalized
emphasis mine):

"The only problem with this sort of success is that TIFF was designed
to be powerful and flexible, at the expense of simplicity.  It takes a
fair amount of effort to handle all the options currently defined in
this specification (PROBABLY NO APPLICATION DOES

In [218]:
train_df.shape

(1657, 3)

In [219]:

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [220]:
d1 = "I love tourist programming"
d2 = "tourist has best programming skills tourist the goat"
d3 = "i love programming"
documents = [d1,d2,d3]
vectors = cv.fit_transform(documents)
print(cv.vocabulary_)
print(vectors)
print(vectors.toarray())

{'love': 3, 'tourist': 7, 'programming': 4, 'has': 2, 'best': 0, 'skills': 5, 'the': 6, 'goat': 1}
  (0, 3)	1
  (0, 7)	1
  (0, 4)	1
  (1, 7)	2
  (1, 4)	1
  (1, 2)	1
  (1, 0)	1
  (1, 5)	1
  (1, 6)	1
  (1, 1)	1
  (2, 3)	1
  (2, 4)	1
[[0 0 0 1 1 0 0 1]
 [1 1 1 0 1 1 1 2]
 [0 0 0 1 1 0 0 0]]


In [221]:

train_df['text'] = train_df['text'].fillna("")


In [222]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

x = cv.fit_transform(train_df['text'])
y = train_df['category']

# cv.vocabulary_
# x.toarray()




In [223]:
from sklearn.naive_bayes import BernoulliNB

nb = BernoulliNB()

nb.fit(x,y)



BernoulliNB()

In [224]:
test_df.dropna(subset=['text'],inplace=True)

In [225]:
test_df.isnull().sum()

text        0
target      0
category    0
dtype: int64

In [226]:
x_test = cv.transform(test_df['text'])
y_test = test_df['category']

In [227]:
pred = nb.predict(x_test)

In [228]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,pred)

0.7083333333333334

In [235]:
from sklearn.feature_extraction.text import TfidfVectorizer

tdv = TfidfVectorizer()

x = tdv.fit_transform(train_df['text'])
y = train_df['category']


In [230]:
from sklearn.naive_bayes import BernoulliNB

nb = BernoulliNB()

nb.fit(x,y)


BernoulliNB()

In [232]:
x_test = tdv.transform(train_df['text'])
y_test = train_df['category']

In [233]:
pred  = nb.predict(x_test)

In [234]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,pred)

0.7899818949909475

In [236]:
from sklearn.naive_bayes import MultinomialNB

mnb = MultinomialNB()

mnb.fit(x,y)

MultinomialNB()

In [237]:
pred = mnb.predict(x_test)

In [238]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,pred)

0.9692214846107423